### ISSUE TITLE
[Safari Issue] Table renders only after hover

### ISSUE THREAD

**Issue by thapapratyush** [zacyu/zacyu.github.io#1]
The table view under Teaching/Resources (besides the first 4) do not render until hovered at. 

Here's the link to the gif:

http://i.imgur.com/QiLOHgq.gif

Might be a Material Design Lite problem.  （＾＿－）

**Comment by zacyu** [comment]
Thanks. Confirmed with Safari 10.0.3 (12602.4.8). Sounds like a Safari problem.

**Comment by zacyu** [comment]
Seems to be related to https://github.com/google/material-design-lite/issues/1194, which has later been reverted in https://github.com/google/material-design-lite/pull/1420. Applying the fix in my custom style for now.

**Comment by zacyu** [comment]
A closer look at it shows that having the button (with drop-down menu) on the card title is also part of the cause of this problem. Since it is determined not to be universal, I'm not opening an issue on MDL.
